#!/usr/bin/env python3
import json, re
from pathlib import Path

SRC = Path('/root/.openclaw/workspace/agency-agents-zh')
OUT = Path(__file__).resolve().parents[1] / 'src/data/expertTemplates.ts'
CATEGORIES = {
    'academic': '学术研究',
    'design': '设计',
    'engineering': '工程开发',
    'finance': '金融财务',
    'game-development': '游戏开发',
    'hr': '人力资源',
    'legal': '法务合规',
    'marketing': '营销运营',
    'paid-media': '付费投放',
    'product': '产品',
    'project-management': '项目管理',
    'sales': '销售',
    'spatial-computing': '空间计算',
    'specialized': '专业领域',
    'strategy': '战略',
    'supply-chain': '供应链',
    'support': '支持职能',
    'testing': '测试质量',
}

def parse_frontmatter(text):
    meta = {}
    body = text
    if text.startswith('---'):
        parts = text.split('---', 2)
        if len(parts) >= 3:
            raw = parts[1]
            body = parts[2].lstrip('\n')
            for line in raw.splitlines():
                if ':' in line:
                    k, v = line.split(':', 1)
                    meta[k.strip()] = v.strip().strip('"\'')
    return meta, body

items = []
for category_dir, category_name in CATEGORIES.items():
    d = SRC / category_dir
    if not d.is_dir():
        continue
    for f in sorted(d.glob('*.md')):
        text = f.read_text(encoding='utf-8')
        meta, body = parse_frontmatter(text)
        name = meta.get('name') or f.stem
        desc = meta.get('description') or ''
        emoji = meta.get('emoji') or ''
        tags = [category_name]
        if '⭐' in text or '中国' in desc or category_dir in {'marketing', 'supply-chain'}:
            tags.append('中国市场')
        items.append({
            'id': f.stem,
            'name': name,
            'category': category_dir,
            'categoryName': category_name,
            'description': desc,
            'emoji': emoji,
            'tags': tags,
            'prompt': text.strip(),
        })

items.sort(key=lambda x: (x['categoryName'], x['name']))
category_rows = [{'id': k, 'name': v, 'count': sum(1 for item in items if item['category'] == k)} for k, v in CATEGORIES.items() if any(item['category'] == k for item in items)]

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("""// Auto-generated by scripts/generate-expert-templates.py. Do not edit manually.
export interface ExpertTemplate {
  id: string
  name: string
  category: string
  categoryName: string
  description: string
  emoji: string
  tags: string[]
  prompt: string
}

export interface ExpertTemplateCategory {
  id: string
  name: string
  count: number
}

export const expertTemplateCategories: ExpertTemplateCategory[] = %s

export const expertTemplates: ExpertTemplate[] = %s
""" % (json.dumps(category_rows, ensure_ascii=False, indent=2), json.dumps(items, ensure_ascii=False, indent=2)), encoding='utf-8')
print(f'generated {len(items)} experts -> {OUT}')
print(f'size {OUT.stat().st_size/1024:.1f} KiB')
